hostname: vccw.local
ip: 192.168.33.99
hostname_aliases:
  - www.vccw.local
lang: ja

plugins: {}
theme: {}
options: {}
multisite_options: {}
wp_debug: false

npms: [
  "browser-sync": "^2.26.7",
  "gulp": "^4.0.2",
  "gulp-sass": "^4.0.2",
  "gulp-autoprefixer": "^6.1.0",
  "gulp-changed": "^4.0.0",
  "gulp-clean-css": "^4.2.0",
  "gulp-connect-php": "^1.0.3",
  "gulp-imagemin": "^6.0.0",
  "gulp-notify": "^3.2.0",
  "gulp-plumber": "^1.2.1",
  "gulp-pug": "^4.0.1",
  "gulp-rename": "^1.4.0",
  "gulp-sourcemaps": "^2.6.5",
  "gulp-uglify": "^3.0.2",
  "gulp-watch": "^5.0.1"
]